package kg.wedevs.advert_bot.bot.handlers.enums;

public enum BaseStateEnums {
    MAIN_SCREEN,
    SELECT_ACTION_ADVERT_SCREEN,
    CREATE_ADVERT_SCREEN,
    SEARCH_ADVERT_SCREEN,
    UPLOAD_PHOTO_SCREEN,
    SELECT_BASE_PHOTO_SCREEN,
    STATISTIC_SCREEN,
    MY_ADVERTS_SCREEN,
    SELECT_PERIOD_SCREEN,
    LOAD_MORE_SCREEN,
    CONFIRM_ADVERT_SCREEN
}
